[alias]
b = "build"
br = "build --release"
r = "run"
rr = "run --release"

[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"

[profile.dev.package."*"]
codegen-backend = "llvm"

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = [
    "-C",
    "link-arg=-fuse-ld=lld",
    "-C",
    "target-cpu=native",
    "-Z",
    "tune-cpu=native",
    "-Z",
    "share-generics=n",
    "-Z",
    "threads=8",
]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C",
    "link-arg=-fuse-ld=mold",
    "-C",
    "target-cpu=native",
    "-Z",
    "tune-cpu=native",
    "-Z",
    "share-generics=y",
    "-Z",
    "threads=8",
]
