# === Mesh config file ===
# Contains vertex and edge information
# Vertices as an array of 3D position information [float, float, float]
# Edges as 2-element arrays of vertex indices [uint, uint]

vertices = [
    [-5.0, 5.0, 0.0],
    [5.0, 5.0, 0.0],
    [5.0, -5.0, 0.0],
    [-5.0, -5.0, 0.0],
    [0.0, 0.0, 11.0]
]

edges = [
    # Pyramid base
    [0, 1],
    [1, 2],
    [2, 3],
    [3, 0],

    # Pyramid edges
    [4, 0],
    [4, 1],
    [4, 2],
    [4, 3]
]